gems:
  - jekyll-seo-tag
  - jekyll-redirect-from

url: https://copperi.ru

collections:
  catalog:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/banner-antiq.jpg