plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
 
url: https://copperi.ru

title: ""
lang: "ru_RU"

collections:
  catalog:
    output: true

defaults:
  -
    scope:
      path: ""
    values:
      image: /images/medniy-polotencesushitel-copperi-caldera.jpg